### ISSUE TITLE
no test.txt in VOC dataset

### ISSUE THREAD

**Issue by nnZidan** [you359/Keras-FasterRCNN#1]
Hi

Traceback (most recent call last):
  File "C:/PY_SOURCE2/RCNN/Keras-FasterRCNN-master/train_frcnn.py", line 99, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "C:\PY_SOURCE2\RCNN\Keras-FasterRCNN-master\keras_frcnn\pascal_voc_parser.py", line 46, in get_data
    with open(imgsets_path_test) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\VOCdevkit\\VOC2012\\ImageSets\\Main\\test.txt'

![2018-10-02_034448](https://user-images.githubusercontent.com/36979192/46317701-b179a980-c5f5-11e8-96c1-9510b1ee4c8c.png)

**Comment by you359** [comment]
Hi @nnZidan 
this repo is simply modified version of keras-frcnn cloned from [https://github.com/yhenon/keras-frcnn/](https://github.com/yhenon/keras-frcnn/) for my own dataset(including testset).
so, i added the code for testset

now, i fixed pascal_voc_parser.py for pascal VOC 2012 dataset(not including testset)
thank to comment!

**Comment by mohammed-Emad** [comment]
Thank you for the reform
Do you have an idea of how to handle data like
icdar2015

**Comment by you359** [comment]
I roughly search icdar2015. this competition has many sub competition.
I think that this challenge mainly deal with a problem like OCR.

However, i'm not yet studied about recognize text in image... 
I'm sorry i can not help you

**Comment by zeehuilin** [comment]
You can use the val.txt as test.txt. :)
Because the val.txt do not use during training.

**Comment by mohammed-Emad** [comment]
Thank you for your attention
