### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by gdut3118007086** [you359/Keras-FasterRCNN#11]
File "train_frcnn.py", line 261, in <module> selected_neg_samples = np.rando

**Comment by gdut3118007086** [comment]
823/1000 [=======================>......] - ETA: 3:08 - rpn_cls: 2.9711 - rpn_regr: 0.0832 - detector_cls: 0.3042 - detector_regr: 0.1486Traceback (most recent call last):
File "train_frcnn.py", line 261, in
selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=False).tolist()
File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "train_frcnn.py", line 263, in
selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=True).tolist()
File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

**Comment by 2017TJM** [comment]
效果巨差，要怎么改进




------------------ 原始邮件 ------------------
发件人: "gdut3118007086"<notifications@github.com>; 
发送时间: 2019年5月1日(星期三) 下午3:06
收件人: "you359/Keras-FasterRCNN"<Keras-FasterRCNN@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [you359/Keras-FasterRCNN] help  (#11)




823/1000 [=======================>......] - ETA: 3:08 - rpn_cls: 2.9711 - rpn_regr: 0.0832 - detector_cls: 0.3042 - detector_regr: 0.1486Traceback (most recent call last):
 File "train_frcnn.py", line 261, in
 selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=False).tolist()
 File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
 ValueError: a must be non-empty
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "train_frcnn.py", line 263, in
 selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=True).tolist()
 File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
 ValueError: a must be non-empty
