### ISSUE TITLE
I am getting error during running training script. Error is : ValueError: Shape must be rank 1 but is rank 0 for 'bn_conv1/Reshape_4' (op: 'Reshape') with input shapes: [1,1,1,64], [].

### ISSUE THREAD

**Issue by parthdhameliya** [you359/Keras-FasterRCNN#20]
Traceback (most recent call last):
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'bn_conv1/Reshape_4' (op: 'Reshape') with input shapes: [1,1,1,64], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\train_frcnn.py", line 147, in <module>
    shared_layers = nn.nn_base(img_input, trainable=True)
  File "F:\Parth\Keras-FasterRCNN\keras_frcnn\resnet.py", line 185, in nn_base
    x = FixedBatchNormalization(axis=bn_axis, name='bn_conv1')(x)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "F:\Parth\Keras-FasterRCNN\keras_frcnn\FixedBatchNormalization.py", line 73, in call
    epsilon=self.epsilon)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 1908, in batch_normalization
    mean = tf.reshape(mean, (-1))
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7178, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\Users\Tharun Raj\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for 'bn_conv1/Reshape_4' (op: 'Reshape') with input shapes: [1,1,1,64], [].

**Comment by wyjun0418** [comment]
modify the kears version to 2.0.3

**Comment by parthdhameliya** [comment]
@wyjun0418 Thank you for your reply.
after modifying the Keras version as you told the error is gone the training starts but it stops and giving this error.

 F .\tensorflow/core/util/mkl util.h:1347] Non-OK-status: Status(error::Code::INVALID_ARGUMENT, "Unsupported data format") status: Invalid argument: Unsupported data format

**Comment by parthdhameliya** [comment]
solved this by updating tensorflow to 1.11.0

**Comment by AhmadShaik** [comment]
Can someone explain the reason behind the error. Is there any other way to solve this error without changing the keras version. Currently I am running with tensorflow 1.13.1, keras 2.2.4.
