### ISSUE TITLE
Setting learning phase for inception_resnet_v2

### ISSUE THREAD

**Issue by collinarnett** [you359/Keras-FasterRCNN#26]
[This](https://stackoverflow.com/questions/42969779/keras-error-you-must-feed-a-value-for-placeholder-tensor-bidirectional-1-keras) issue leads me to believe that I simply need to insert a bit of code into the classifier method under `inception_resnet_v2.py` but I don't know if this is necessary since it seemed fined training initially. It's only having this problem when predicting.

```
Traceback (most recent call last):
  File "test_frcnn.py", line 199, in <module>
    [P_cls, P_regr] = model_classifier_only.predict([F, ROIs])
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/keras/engine/training.py", line 1573, in predict
    batch_size=batch_size, verbose=verbose)
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/keras/engine/training.py", line 1203, in _predict_loop
    batch_outs = f(ins_batch)
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2103, in __call__
    feed_dict=feed_dict)
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Stem_block_conv1_bn/keras_learning_phase' with dtype bool
	 [[node Stem_block_conv1_bn/keras_learning_phase (defined at /Users/carnett/apps/python-virtual-environments/keras_fasterrcnn/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:103) ]]
```

**Comment by collinarnett** [comment]
It seems if you use newer versions of Keras, this problem does not happen. I would like someone else to confirm this for me.

**Comment by collinarnett** [comment]
Updating to the latest version of this keras fixed this issue for me.
