### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wudi00** [you359/Keras-FasterRCNN#42]
I had this problem during training. And what's wrong with this, please? Thanks.
`Traceback (most recent call last):
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 30 of dimension 1 out of bounds.
         [[{{node roi_pooling_conv_1/strided_slice_152}}]]
         [[{{node add_22}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_frcnn.py", line 286, in <module>
    loss_class = model_classifier.train_on_batch([X, X2[:, sel_samples, :]], [Y1[:, sel_samples, :], Y2[:, sel_samples, :]])
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1621, in train_on_batch
    outputs = self.train_function(ins)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2103, in __call__
    feed_dict=feed_dict)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 30 of dimension 1 out of bounds.
         [[node roi_pooling_conv_1/strided_slice_152 (defined at /media/disk/wudi/Keras-FasterRCNN-master/keras_frcnn/RoiPoolingConv.py:67) ]]
         [[node add_22 (defined at /media/disk/wudi/.local/lib/python3.6/site-packages/keras/engine/training.py:906) ]]

Caused by op 'roi_pooling_conv_1/strided_slice_152', defined at:
  File "train_frcnn.py", line 157, in <module>
    classifier = nn.classifier(shared_layers, roi_input, C.num_rois, nb_classes=len(classes_count), trainable=True)
  File "/media/disk/wudi/Keras-FasterRCNN-master/keras_frcnn/resnet.py", line 245, in classifier
    out_roi_pool = RoiPoolingConv(pooling_regions, num_rois)([base_layers, input_rois])
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/media/disk/wudi/Keras-FasterRCNN-master/keras_frcnn/RoiPoolingConv.py", line 67, in call
    w = rois[0, roi_idx, 2]
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 654, in _slice_helper
    name=name)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 820, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 9356, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): slice index 30 of dimension 1 out of bounds.
         [[node roi_pooling_conv_1/strided_slice_152 (defined at /media/disk/wudi/Keras-FasterRCNN-master/keras_frcnn/RoiPoolingConv.py:67) ]]
         [[node add_22 (defined at /media/disk/wudi/.local/lib/python3.6/site-packages/keras/engine/training.py:906) ]]
`

**Comment by AlpTuncay** [comment]
I just had this issue recently. Any suggestions how to solve this?

**Comment by collinarnett** [comment]
Diagnosing dimension out of bounds errors is pretty hard since it could be a lot of things. Try using my pull request since I fixed a lot of issues with the repository there. If that doesn't fix your issue I can try diagnosing with you.

**Comment by AlpTuncay** [comment]
@collinarnett  there was a try/except block which was commented. What I did was, before you mentioned your PR, I removed the comments so that whole training process is inside a try/except block. It works but from time to time exception is caught. Would you be able to explain what is the main reason of this exception? How does it affect the training performance and as a result testing performance?

**Comment by collinarnett** [comment]
As far as I know ROI Pooling is responsible for finding the location of the desired object by taking the best same from a region as outlined in more detail [here](https://deepsense.ai/region-of-interest-pooling-explained/). For this error, I would guess that the sliding window is overlapping out of bounds and if you're putting the entire training loop in a try except block, it would skip the training step. 

I think the easiest way to diagnose this problem would be to test the ROI *width* as indicated by @wudi00 's error:
```
File "/media/disk/wudi/Keras-FasterRCNN-master/keras_frcnn/RoiPoolingConv.py", line 67, in call
w = rois[0, roi_idx, 2]
```
