### ISSUE TITLE
Training fails after some epochs passed.

### ISSUE THREAD

**Issue by AlpTuncay** [you359/Keras-FasterRCNN#46]
In the training phase, after some epoch, the following exception is thrown:
`Traceback (most recent call last):
  File "train_frcnn.py", line 288, in <module>
    loss_class = model_classifier.train_on_batch([X, X2[:, sel_samples, :]], [Y1[:, sel_samples, :], Y2[:, sel_samples, :]])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: slice index 20 of dimension 1 out of bounds.
	 [[{{node roi_pooling_conv_1/strided_slice_102}}]]
	 [[loss_1/add/_811]]
  (1) Invalid argument: slice index 20 of dimension 1 out of bounds.
	 [[{{node roi_pooling_conv_1/strided_slice_102}}]]
0 successful operations.
0 derived errors ignored.`

Are there any solutions to this issue?

**Comment by saleed** [comment]
I got the same error, have you solved this problem?

**Comment by AlpTuncay** [comment]
@saleed unfortunately, I do not have a solution to this. I just wrapped the whole training block with try except in order to continue training, as a result when the exception occurs it skips the training step. This error might be related to these lines in RoiPoolingConv :

```python
for roi_idx in range(self.num_rois):
    x = rois[0, roi_idx, 0]
    y = rois[0, roi_idx, 1]
    w = rois[0, roi_idx, 2]
    h = rois[0, roi_idx, 3]
```
If you inspect this issue #42 it has the full traceback and I think it points to these lines. I thought, writing a for each loop in these lines would solve the problem but never got to test it out. Indeed `roi_idx` might be out of bounds here and I do not know if we are guaranteed to have `self.num_rois` number of ROIs at each training step.
