### ISSUE TITLE
help! it doesn't begin!

### ISSUE THREAD

**Issue by chenjjjjuu** [you359/Keras-FasterRCNN#53]
Using TensorFlow backend.
Parsing annotation files
Processing 2012_002286.xml: 100%|███████| 17125/17125 [00:08<00:00, 1933.86it/s]
Training images per class:
{'aeroplane': 954,
 'bg': 0,
 'bicycle': 790,
 'bird': 1221,
 'boat': 999,
 'bottle': 1482,
 'bus': 637,
 'car': 2364,
 'cat': 1227,
 'chair': 2906,
 'cow': 702,
 'diningtable': 747,
 'dog': 1541,
 'horse': 750,
 'motorbike': 751,
 'person': 10129,
 'pottedplant': 1099,
 'sheep': 994,
 'sofa': 786,
 'train': 656,
 'tvmonitor': 826}
Num classes (including bg) = 21
Config has been written to config.pickle, and can be loaded when testing to ensure correct results
Num train samples 0
Num test samples 0
loading weights from resnet50_weights_tf_dim_ordering_tf_kernels.h5
Could not load pretrained model weights. Weights can be found in the keras application folder         https://github.com/fchollet/keras/tree/master/keras/applications
2020-04-30 12:17:02.208461: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-30 12:17:02.315812: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-30 12:17:02.316910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 5.94GiB freeMemory: 5.60GiB
2020-04-30 12:17:02.316931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-04-30 12:17:02.716655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-30 12:17:02.716706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-04-30 12:17:02.716718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-04-30 12:17:02.717023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5375 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Starting training
Epoch 1/2000
^CTraceback (most recent call last):
  File "train_frcnn.py", line 220, in <module>
    X, Y, img_data = next(data_gen_train)
  File "/home/chen/chen/Keras-FasterRCNN-master/keras_frcnn/data_generators.py", line 284, in get_anchor_gt
    random.shuffle(all_img_data)
  File "/home/chen/.virtualenvs/p3cv4/lib/python3.5/random.py", line 268, in shuffle
    randbelow = self._randbelow
KeyboardInterrupt
(p3cv4) chen@chen-TM1705:~/chen/Keras-FasterRCNN-master$ python3 train_frcnn.py -p./pascalvoc
Using TensorFlow backend.
Parsing annotation files
Processing 2012_002286.xml: 100%|███████| 17125/17125 [00:08<00:00, 1960.77it/s]
Training images per class:
{'aeroplane': 954,
 'bg': 0,
 'bicycle': 790,
 'bird': 1221,
 'boat': 999,
 'bottle': 1482,
 'bus': 637,
 'car': 2364,
 'cat': 1227,
 'chair': 2906,
 'cow': 702,
 'diningtable': 747,
 'dog': 1541,
 'horse': 750,
 'motorbike': 751,
 'person': 10129,
 'pottedplant': 1099,
 'sheep': 994,
 'sofa': 786,
 'train': 656,
 'tvmonitor': 826}
Num classes (including bg) = 21
Config has been written to config.pickle, and can be loaded when testing to ensure correct results
Num train samples 0
Num test samples 0
loading weights from resnet50_weights_tf_dim_ordering_tf_kernels.h5
Could not load pretrained model weights. Weights can be found in the keras application folder         https://github.com/fchollet/keras/tree/master/keras/applications
2020-04-30 12:25:23.276490: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-30 12:25:23.400670: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-30 12:25:23.401476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 5.94GiB freeMemory: 5.60GiB
2020-04-30 12:25:23.401493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-04-30 12:25:23.806395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-30 12:25:23.806431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-04-30 12:25:23.806439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-04-30 12:25:23.806763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5366 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
Starting training
Epoch 1/2000
 and then there no progress bar? how can I do

**Comment by AlpTuncay** [comment]
Previously, in simple_parser, training data was saved into the imageset of "trainval" but in the train_frcnn script it was trying to fetch the data from imageset of "train".
In simple_parser.py
` if np.random.randint(0,6) > 0:
                    all_imgs[filename]['imageset'] = 'trainval'
                else:
                    all_imgs[filename]['imageset'] = 'test'
`
In train_frcnn.py
`
train_imgs = [s for s in all_imgs if s['imageset'] == 'train']
test_imgs = [s for s in all_imgs if s['imageset'] == 'test']
`
These are the previous versions of the snippets. With the latest merge, this issue should be fixed I believe, if it is not caused by something else somehow.

**Comment by AlpTuncay** [comment]
Something recently happened to me, I am using Colab for training and previously they had support for Python 2. For the past few days, I couldn't set the environment to use Python 2 and whenever I try running the code with Python 3, it does not begin and I get no errors. Something similar to your situation.
