### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 14 of dimension 1 out of bounds. 	

### ISSUE THREAD

**Issue by saleed** [you359/Keras-FasterRCNN#59]
when I changed the epoch to 10 and image epoch length to 1000 , i got this error:

2020-05-21 16:51:09.814678: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: slice index 15 of dimension 1 out of bounds.
2020-05-21 16:51:09.814360: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: slice index 7 of dimension 1 out of bounds.
2020-05-21 16:51:09.814156: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: slice index 1 of dimension 1 out of bounds.
2020-05-21 16:51:09.814616: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at strided_slice_op.cc:107 : Invalid argument: slice index 20 of dimension 1 out of bounds.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 14 of dimension 1 out of bounds.
	 [[{{node roi_pooling_conv_1/strided_slice_71}}]]
does anybody know what happens? thanks!

**Comment by Tian-YS** [comment]
Hi，did you deal with this problem？I have the same problem when i use my datasets.

and before this problem happen, it show me the mean_overlapping_bboxes == 0.

**Comment by saleed** [comment]
not sloved yet, I give up and use another project

> Hi，did you deal with this problem？I have the same problem when i use my datasets.
> 
> and before this problem happen, it show me the mean_overlapping_bboxes == 0.

not sloved yet, I give up and use another project
