### ISSUE TITLE
ValueError: a must be non-empty

### ISSUE THREAD

**Issue by bzburr** [you359/Keras-FasterRCNN#6]
823/1000 [=======================>......] - ETA: 3:08 - rpn_cls: 2.9711 - rpn_regr: 0.0832 - detector_cls: 0.3042 - detector_regr: 0.1486Traceback (most recent call last):
  File "train_frcnn.py", line 261, in <module>
    selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=False).tolist()
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_frcnn.py", line 263, in <module>
    selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=True).tolist()
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty

**Comment by kkawtar** [comment]
did you found a solution for that ?

**Comment by hodaatef** [comment]
any one solved this error please???

**Comment by attilab97** [comment]
if len(neg_samples) != 0:
                try:
                    selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=False).tolist()
                except:
                    selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=True).tolist()
 Just put a test before selecting negative samples.

**Comment by gdut3118007086** [comment]
> 
> 
> if len(neg_samples) != 0:
> try:
> selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=False).tolist()
> except:
> selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=True).tolist()
> Just put a test before selecting negative samples.

after that i meet another question


  File "train_frcnn.py", line 275, in <module>
    loss_class = model_classifier.train_on_batch([X, X2[:, sel_samples, :]], [Y1[:, sel_samples, :], Y2[:, sel_samples, :]])
IndexError: index 4 is out of bounds for axis 1 with size 1

**Comment by gdut3118007086** [comment]
(any one solved this error please???)

**Comment by huogy** [comment]
> (any one solved this error please???)

This is a version issue，you need numpy==1.11.0

**Comment by AdamJochna** [comment]
if C.num_rois > 1:
            if len(pos_samples) < C.num_rois//2:
                selected_pos_samples = pos_samples.tolist()
            else:
                if len(pos_samples) > 0:
                    selected_pos_samples = np.random.choice(pos_samples, C.num_rois//2, replace=False).tolist()
                else:
                    selected_pos_samples = []
            try:
                if len(neg_samples) > 0:
                    selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=False).tolist()
                else:
                    selected_neg_samples = []
            except:
                if len(neg_samples) > 0:
                    selected_neg_samples = np.random.choice(neg_samples, C.num_rois - len(selected_pos_samples), replace=True).tolist()
                else:
                    selected_neg_samples = []

            sel_samples = selected_pos_samples + selected_neg_samples
        else:

**Comment by AdamJochna** [comment]
that seems to solve this issue

**Comment by WindyXiang** [comment]
I also met this problem. Anyone solve that? Help...
