### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'output_masks'

### ISSUE THREAD

**Issue by danilosouza1896** [you359/Keras-FasterRCNN#84]
I'm trying to train my dataset, but the application has returned a problem:

I'm using simple parser

Traceback (most recent call last):
  File "train_frcnn.py", line 130, in <module>
    shared_layers = nn.nn_base(img_input, trainable=True)
  File "/home/user/projetotcc/keras_frcnn/resnet.py", line 176, in nn_base
    x = ZeroPadding2D((3, 3))(img_input)
  File "/home/user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/keras/engine/base_layer.py", line 443, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/home/user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'

**Comment by So-dal** [comment]
Hi, I got the same issue when I try to run the model on tf-gpu 2, but if I use tf-gpu 1.13 or 1.14 it's OK. Which version of tensorflow do you use ?
